apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: go-component-sample-multi-component
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/cqi-tenant/sample-multi-component/go-component-sample-multi-component@sha256:5ce68783dd4a0be0d2ee6fe90afdc00a4ea0b5eaad4b8fdb2f37cb20a185884d
        name: my-go
        resources: {}
status: {}
