apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-component-sample-multi-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-component-sample-multi-component
    app.kubernetes.io/part-of: sample-multi-component
  name: python-component-sample-multi-component
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: python-component-sample-multi-component
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: python-component-sample-multi-component
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/cqi-tenant/sample-multi-component/python-component-sample-multi-component@sha256:1143e62e4096492815763c3a4969b30246bc1c60bbedd7dd22161fc3d12d12a3
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
