apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: go-component-sample-multi-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-component-sample-multi-component
    app.kubernetes.io/part-of: sample-multi-component
  name: go-component-sample-multi-component
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: go-component-sample-multi-component
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: go-component-sample-multi-component
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/cqi-tenant/sample-multi-component/go-component-sample-multi-component@sha256:04e46d9561f5dc84311b1adde670047be5a63c938fbfeb5d52e158c9e3f62a10
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
