apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: python-component-sample-multi-component
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/cqi-tenant/sample-multi-component/python-component-sample-multi-component@sha256:2e80428fff0749618566c6098b53ac1ff7e7d647b3043b697e0e514953910d7e
        name: my-python
        resources: {}
status: {}
