apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: python-component-sample-multi-component
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/cqi-tenant/sample-multi-component/python-component-sample-multi-component@sha256:f13d2396f47133bc96568d571b799fe108283f6859369a7761a4501837930e76
        name: my-python
        resources: {}
status: {}
