apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: python-component-sample-multi-component
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/cqi-tenant/sample-multi-component/python-component-sample-multi-component@sha256:b0ea90e7b223a6dceb1d893ed6f51ef2e41a7eb5c8f36c4f3546884025fe60dc
        name: my-python
        resources: {}
status: {}
