apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-component-sample-multi-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-component-sample-multi-component
    app.kubernetes.io/part-of: sample-multi-component
  name: python-component-sample-misqz
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: python-component-sample-multi-component
    weight: null
status: {}
